name: "doctest-tensorflow"

env:
  FILE: "content/TensorFlow.py"

on:
  push:
    paths:
      - "content/TensorFlow.py"
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Convert .py file to doctest
        run: |
          mkdir temp
          python utils/convert_py_to_doctest.py "$FILE" temp/test_doctest.py
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          SHELL_COMMAND_MARKER="$(python -c "from utils import config; print(config.SHELL_COMMAND_MARKER)")"

          while read -r line; do
            echo "$line"
            eval "$line"
          done < <(grep "$SHELL_COMMAND_MARKER" "$FILE" | sed "s/$SHELL_COMMAND_MARKER//")

          cat temp/test_doctest.py

          pytest temp --doctest-modules --doctest-continue-on-failure --color=yes
