name: Pull request

on:
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install tensorflow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          mkdir temp
          python utils/convert_py_to_doctest.py content/TensorFlow.py temp/test_TensorFlow.py
          pytest temp --doctest-modules --doctest-continue-on-failure --color=yes
