name: Pull request

on:
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Get changed files in the content folder
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: content/*.py
      - name: Test with pytest and doctest
        run: |
          SHELL_COMMAND_MARKER="$(python -c "from utils import config; print(config.SHELL_COMMAND_MARKER)")"

          for FILE in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$FILE was changed"

            mkdir temp
            echo "Convert .py file to doctest"
            python utils/convert_py_to_doctest.py "$FILE" temp/test_doctest.py

            echo "Run shell commands marked in the file"
            while read -r line; do
              echo "$line"
              eval "$line"
            done < <(grep "$SHELL_COMMAND_MARKER" "$FILE" | sed "s/$SHELL_COMMAND_MARKER//")

            echo "Test with pytest and doctest"
            cat temp/test_doctest.py
            pytest temp/test_doctest.py --doctest-modules --doctest-continue-on-failure --color=yes
          done
